//! Dual-hash difference classification for AXIOM / DCK (v2.3).
//! HashA (Invariant) / HashB (Semantic); State / Semantic / Constraint differences.

use serde::{Deserialize, Serialize};

// ---------------------------------------------------------------------------
// Hash identities
// ---------------------------------------------------------------------------

/// Invariant / physical hash — sealed by ACP, treated as Ground Truth.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct HashA {
    pub value: String,
}

impl HashA {
    pub fn new(value: impl Into<String>) -> Self {
        Self {
            value: value.into(),
        }
    }

    pub fn same_as(&self, other: &HashA) -> bool {
        self.value == other.value
    }
}

/// Semantic / interpretation hash — may be regenerated by models or humans.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct HashB {
    pub value: String,
}

impl HashB {
    pub fn new(value: impl Into<String>) -> Self {
        Self {
            value: value.into(),
        }
    }

    pub fn same_as(&self, other: &HashB) -> bool {
        self.value == other.value
    }
}

/// Sealed pair after PLP → Capsule → ACP (A) and after interpretation (B).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct DualHashSnapshot {
    pub hash_a: HashA,
    pub hash_b: HashB,
    /// Optional constraint fingerprint derived from A (e.g. sorted constraint ids).
    pub constraint_id: Option<String>,
}

impl DualHashSnapshot {
    pub fn new(hash_a: HashA, hash_b: HashB) -> Self {
        Self {
            hash_a,
            hash_b,
            constraint_id: None,
        }
    }

    pub fn with_constraint(mut self, constraint_id: impl Into<String>) -> Self {
        self.constraint_id = Some(constraint_id.into());
        self
    }
}

// ---------------------------------------------------------------------------
// Difference classes
// ---------------------------------------------------------------------------

/// Primary dual-hash classification (A×B matrix).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum DualHashClass {
    /// A same, B same — no dual-hash difference.
    None,
    /// A same, B changed — interpretation / semantic drift.
    Semantic,
    /// A changed, B same — state / physical / input identity change.
    State,
    /// Both changed — compound.
    Compound,
}

impl DualHashClass {
    pub fn from_pair(a_same: bool, b_same: bool) -> Self {
        match (a_same, b_same) {
            (true, true) => DualHashClass::None,
            (true, false) => DualHashClass::Semantic,
            (false, true) => DualHashClass::State,
            (false, false) => DualHashClass::Compound,
        }
    }

    pub fn as_str(self) -> &'static str {
        match self {
            DualHashClass::None => "None",
            DualHashClass::Semantic => "Semantic",
            DualHashClass::State => "State",
            DualHashClass::Compound => "Compound",
        }
    }
}

/// Constraint validation outcome: B against Constraint(A).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ConstraintVerdict {
    /// B satisfies constraints implied by A.
    Pass,
    /// B violates or diverges from constraints of A (hallucination / invalid interpretation).
    Fail,
    /// Constraints not supplied — not evaluated.
    NotEvaluated,
}

impl ConstraintVerdict {
    pub fn as_str(self) -> &'static str {
        match self {
            ConstraintVerdict::Pass => "Pass",
            ConstraintVerdict::Fail => "Fail",
            ConstraintVerdict::NotEvaluated => "NotEvaluated",
        }
    }

    pub fn is_constraint_difference(self) -> bool {
        matches!(self, ConstraintVerdict::Fail)
    }
}

/// Unified difference taxonomy used by DCK measurement.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum DifferenceKind {
    /// No dual-hash or constraint difference.
    None,
    /// State Difference — Hash A changed.
    State,
    /// Semantic Difference — Hash B changed under same A.
    Semantic,
    /// Constraint Difference — B fails Validate against Constraint(A).
    Constraint,
    /// Compound — A and B both changed (may coexist with Constraint).
    Compound,
}

impl DifferenceKind {
    pub fn as_str(self) -> &'static str {
        match self {
            DifferenceKind::None => "None",
            DifferenceKind::State => "State",
            DifferenceKind::Semantic => "Semantic",
            DifferenceKind::Constraint => "Constraint",
            DifferenceKind::Compound => "Compound",
        }
    }
}

// ---------------------------------------------------------------------------
// Evaluation result
// ---------------------------------------------------------------------------

/// Full dual-hash + constraint evaluation for DCK / CI / Golden Vectors.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct DualHashEvaluation {
    pub class: DualHashClass,
    pub constraint: ConstraintVerdict,
    /// Primary kind for logging / routing (Constraint takes priority when Fail).
    pub primary_kind: DifferenceKind,
    /// True if any of State / Semantic / Constraint / Compound is active.
    pub has_difference: bool,
    pub a_same: bool,
    pub b_same: bool,
}

impl DualHashEvaluation {
    /// Classify from two snapshots and an optional constraint check.
    ///
    /// `constraint_ok`:
    /// - `Some(true)`  → Pass
    /// - `Some(false)` → Fail (Constraint Difference)
    /// - `None`        → NotEvaluated
    pub fn evaluate(
        baseline: &DualHashSnapshot,
        current: &DualHashSnapshot,
        constraint_ok: Option<bool>,
    ) -> Self {
        let a_same = baseline.hash_a.same_as(&current.hash_a);
        let b_same = baseline.hash_b.same_as(&current.hash_b);
        let class = DualHashClass::from_pair(a_same, b_same);

        let constraint = match constraint_ok {
            Some(true) => ConstraintVerdict::Pass,
            Some(false) => ConstraintVerdict::Fail,
            None => ConstraintVerdict::NotEvaluated,
        };

        // Primary kind: Constraint Difference is orthogonal and high priority when Fail.
        let primary_kind = if constraint.is_constraint_difference() {
            DifferenceKind::Constraint
        } else {
            match class {
                DualHashClass::None => DifferenceKind::None,
                DualHashClass::Semantic => DifferenceKind::Semantic,
                DualHashClass::State => DifferenceKind::State,
                DualHashClass::Compound => DifferenceKind::Compound,
            }
        };

        let has_difference = primary_kind != DifferenceKind::None
            || class != DualHashClass::None
            || constraint.is_constraint_difference();

        Self {
            class,
            constraint,
            primary_kind,
            has_difference,
            a_same,
            b_same,
        }
    }

    /// Convenience: no constraint check.
    pub fn evaluate_hashes_only(
        baseline: &DualHashSnapshot,
        current: &DualHashSnapshot,
    ) -> Self {
        Self::evaluate(baseline, current, None)
    }
}

// ---------------------------------------------------------------------------
// Constraint validation hook (pure)
// ---------------------------------------------------------------------------

/// Pure constraint check: does semantic payload `b_payload` satisfy
/// constraints declared under Hash A / constraint_id?
///
/// Callers supply a predicate (e.g. length limits, forbidden structures,
/// required fields from PSS). This keeps DCK free of domain knowledge.
pub fn validate_constraint<F>(constraint_id: Option<&str>, b_payload: &str, check: F) -> ConstraintVerdict
where
    F: Fn(Option<&str>, &str) -> bool,
{
    if constraint_id.is_none() && b_payload.is_empty() {
        return ConstraintVerdict::NotEvaluated;
    }
    if check(constraint_id, b_payload) {
        ConstraintVerdict::Pass
    } else {
        ConstraintVerdict::Fail
    }
}
